[package]
name = "kleisli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#"tool" = "0.2.1"
"fp_rust" = "0.3.5"